name: Tests

on:
  push:
    branches:
      - '**'

    tags-ignore:
      - '**'

  pull_request:
    branches:
      - '**'

    tags-ignore:
      - '**'

jobs:
  # Run pre-commit Checks
  pre-commit:
    name: Pre Commit Checks
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: 'pyproject.toml' # Read the Python version from the pyproject.toml file

      # Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          # https://endoflife.date/nodejs
          node-version: '20' # [LTS] End of Life: 30 Apr 2026
      - run: npm install

      - name: Run Pre Commit Checks
        uses: pre-commit/action@v3.0.1

  # Pypi Build Test
  pypi-build-test:
    needs: [ pre-commit ]
    name: PyPi Build Test
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: 'pyproject.toml' # Read the Python version from the pyproject.toml file

      # Install Tools
      - name: Install Tools
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade build
          python -m pip install --upgrade setuptools wheel

      # Build Package
      - name: Package Build
        env:
          STACKMANAGER_VERSION: 9999
        run: |
          python -m build

      # Upload Build Artifacts
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ github.event_name }}-${{ github.sha }}
          path: dist
          if-no-files-found: ignore
